[phases.setup]
nixPkgs = ["nodejs_22", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "curl -fsSL https://deno.land/install.sh | sh"
]

[start]
cmd = "export PATH=$HOME/.deno/bin:$PATH && npm start"